"""
Job ID generation and helper utilities for the runner layer.
"""
from __future__ import annotations

import uuid


def generate_job_id(repo: str, issue_number: int) -> str:
    """
    Generate a unique, human-friendly job ID.
    Example: job_shrinkly_42_a3f9
    """
    repo_slug = repo.split("/")[-1].lower().replace("-", "_")[:20]
    suffix = uuid.uuid4().hex[:4]
    return f"job_{repo_slug}_{issue_number}_{suffix}"


def make_branch_name(issue_number: int) -> str:
    """Return the standardised branch name for an issue."""
    return f"ai/issue-{issue_number}"


def make_commit_message(issue_title: str, issue_number: int) -> str:
    """
    Generate a conventional commit message.
    Example: 'feat: Add PDF compression\n\nCloses #42'
    """
    # Simple type detection
    title_lower = issue_title.lower()
    if any(w in title_lower for w in ("fix", "bug", "error", "crash", "broken")):
        commit_type = "fix"
    elif any(w in title_lower for w in ("test", "spec", "coverage")):
        commit_type = "test"
    elif any(w in title_lower for w in ("doc", "readme", "comment")):
        commit_type = "docs"
    elif any(w in title_lower for w in ("refactor", "clean", "rename", "reorganize")):
        commit_type = "refactor"
    elif any(w in title_lower for w in ("chore", "config", "setup", "ci")):
        commit_type = "chore"
    else:
        commit_type = "feat"

    # Shorten title for commit summary line
    short_title = issue_title[:60] if len(issue_title) > 60 else issue_title
    return f"{commit_type}: {short_title}\n\nCloses #{issue_number}"


def make_pr_title(issue_title: str) -> str:
    title_lower = issue_title.lower()
    if any(w in title_lower for w in ("fix", "bug", "error", "crash")):
        prefix = "fix"
    else:
        prefix = "feat"
    return f"{prefix}: {issue_title}"


def make_pr_body(
    issue_number: int,
    issue_title: str,
    agent_name: str,
    summary: str,
    files_changed: list[str],
    validation_results: str,
) -> str:
    if files_changed:
        files_str = "\n".join(f"- `{f}`" for f in files_changed)
    else:
        files_str = "- (no files listed)"

    return f"""## Summary

This Pull Request was automatically generated by the AI Coding Agent using **{agent_name}**.

{summary}

## Changes

{files_str}

## Validation

{validation_results}

## Related Issue

Closes #{issue_number}

---
*Generated automatically for: {issue_title}*
"""
